Инкремент 13
yury-kuznetsov/shortener pull request #14
Opened 2023-11-15 18:41 UTC by yury-kuznetsov

2023-11-16 09:10 UTC, edylcrm requested changes

2023-11-16 09:10 UTC, edylcrm commented on internal/storage/database/storage.go
> +type Storage struct{}
[BLOCKER] Чтобы каждый раз не открывать соединение к psql лучше сделать так:
```
type Storage struct {
    db *sql.DB
}

func NewStorage(db *sql.DB) *Storage {
    return &Storage{db: db}
}
```

2023-11-16 09:10 UTC, edylcrm commented on internal/storage/database/storage.go
> +	row := db.QueryRowContext(ctx, "SELECT uri FROM urls WHERE code = $1", code)
[BLOCKER] и здесь использовать как 
```
s.db.QueryRowContext(ctx, "SELECT uri FROM urls WHERE code = $1", code)
```

2023-11-16 09:10 UTC, edylcrm commented on internal/storage/database/storage.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
[BLOCKER] здесь лучше не создавать новый контекст, а получать контекст из request. Если по какой-то причине клиент отменит запрос, то контекст будет отменен и лишний запрос делаться не будет.
Нужно изменить сигнатуру метода на `Get(ctx context.Context, code string) (string, error)`

2023-11-16 09:10 UTC, edylcrm commented on internal/storage/database/storage.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
[BLOCKER] тоже самое что и выше с context

2023-11-16 09:10 UTC, edylcrm commented on internal/storage/database/storage.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
[BLOCKER] тоже самое что и выше с context

2023-11-19 21:22 UTC, yury-kuznetsov commented on internal/storage/database/storage.go
> +type Storage struct{}
Мм, "каждый раз не открывать" равносильно "каждый раз не закрывать". Меня смутные сомнения терзают по этому поводу. Правильно ли держать соединение с базой открытым все время?

Поправил!

2023-11-20 08:35 UTC, edylcrm commented on internal/storage/database/storage.go
> +type Storage struct{}
Да, при большой нагрузке обычно делается пул соединений, чтобы каждый раз не подключаться по новой. Здесь такие же преимущества, что и держать TCP соединения.

2023-11-25 19:27 UTC, merged