Спринт 1
yury-kuznetsov/shortener pull request #6
Opened 2023-10-14 16:45 UTC by yury-kuznetsov

# Итоговый PR первого спринта
Состоит из 5 инкрементов:
- #1 
- #2
- #3
- #4
- #5

## Выполненная работа
### 1 инкремент
- развертывание пустого http-сервера;
- создание пакета uricoder (URI-coder);
- подключение пакета к серверу через хандлеры.
### 2 инкремент
- подключена библиотека `testify`;
- создание теста для storage;
- создание теста для uricoder;
- создание теста для handlers;
- создание теста для main.
### 3 инкремент
- подключен роутер `chi`;
- использование роутера `chi`.
### 4 инкремент
- создание конфигурации;
- подключение конфигурации.
### 5 инкремент
- обработка переменных окружения.

## Todo
IDE-шный анализатор жалуется на `defer res.Body.Close()` и просит его реализовать по-другому:
```go
defer func(Body io.ReadCloser) {
	err := Body.Close()
	if err != nil {
		
	}
}(res.Body)
```
Но на такую конструкцию уже жалуется чекер автотестов с пайплайна. 
- [ ] Поднять этот вопрос в чате или на созвоне.
- [ ] Возможно, есть смысл реализовать конфигурацию через синглтон config.Get() - уточнить у ревьюера. 
- [ ] Перейти с `tab` на 4 пробела (а точно надо?).

2023-10-17 07:50 UTC, edylcrm requested changes

2023-10-17 07:50 UTC, edylcrm commented on cmd/config/config.go
> +package config
Комментарии разделены на несколько типов:
**[BLOCKER]** - Проблема, не решив которую принять работу нельзя
**[LINT]** - Заменичение, опционально к выполнению
**[FYI]** - просто ремарка

2023-10-17 07:50 UTC, edylcrm commented on cmd/storage/storage.go
> +package storage
**[BLOCKER]** Давай это унесем в internal. Получается половина бизнес логики здесь, половина в internal.

2023-10-17 07:50 UTC, edylcrm commented on cmd/uricoder/uricoder.go
> +package uricoder
**[BLOCKER]** Давай это унесем в internal. Получается половина бизнес логики здесь, половина в internal.

2023-10-17 07:50 UTC, edylcrm commented on cmd/shortener/main.go
> +	if err := http.ListenAndServe(config.Options.HostAddr, r); err != nil {
[FYI] Здесь так же было бы хорошо слушать сигналы ОС и корректно завершать http сервис чтобы пользователи в момент редеплоя приложения или принудительного завершения получили ответ.
Пример работы с сигналами: https://gobyexample.com/signals
Как корректно завершать http сервис: https://pkg.go.dev/net/http#Server.SetKeepAlivesEnabled и https://pkg.go.dev/net/http#Server.Shutdown

2023-10-17 07:50 UTC, edylcrm commented on cmd/storage/storage.go
> +var ArrStorage = make(Storage)
**[BLOCKER]** лучше не использовать глобальные переменные и инициализировать структуру там где это нужно

2023-10-17 07:50 UTC, edylcrm commented on cmd/storage/storage.go
> +func (s Storage) Get(code string) string {
**[LINT]** здесь лучше использовать ресивер чтобы структура каждый раз не покировалась.
```
func (s *Storage) Get(code string) string
func (s *Storage) Set(value string) string
```

2023-10-17 07:50 UTC, edylcrm commented on internal/app/handlers.go
> +func getCoder() *uricoder.Coder {
**[LINT]** А зачем при каждом запросе пользователя создавать новый uricoder? При больших нагрузках здесь может быть проблема с потреблением памяти и работе GC. Можно один раз его создать в main и передавать как зависимость в handlers

2023-10-20 09:15 UTC, yury-kuznetsov commented on cmd/storage/storage.go
> +package storage
✅

2023-10-20 09:15 UTC, yury-kuznetsov commented on cmd/uricoder/uricoder.go
> +package uricoder
✅

2023-10-20 09:16 UTC, yury-kuznetsov commented on cmd/storage/storage.go
> +var ArrStorage = make(Storage)
Понял. Заменил на `NewStorage`.

2023-10-20 09:17 UTC, yury-kuznetsov commented on cmd/storage/storage.go
> +func (s Storage) Get(code string) string {
✅

2023-10-20 09:17 UTC, yury-kuznetsov commented on internal/app/handlers.go
> +func getCoder() *uricoder.Coder {
✅

2023-10-20 09:20 UTC, yury-kuznetsov commented on cmd/shortener/main.go
> +	if err := http.ListenAndServe(config.Options.HostAddr, r); err != nil {
Спасибо за наводку. Прочитал, ознакомился. 

В работу не брал, чтобы не увеличивать сейчас объем кода. На выпускной работе учту.

2023-10-23 07:57 UTC, edylcrm approved these changes

2023-10-27 07:14 UTC, merged